// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:         string;
    type:       string;
    place_type: string[];
    relevance:  number;
    properties: Properties;
    text:       string;
    place_name: string;
    bbox?:      number[];
    center:     number[];
    geometry:   Geometry;
    context:    Context[];
}

export interface Context {
    id:          string;
    short_code?: ShortCode;
    wikidata?:   Wikidata;
    text:        string;
}

export enum ShortCode {
    MX = "mx",
    MXGro = "MX-GRO",
}

export enum Wikidata {
    Q60158 = "Q60158",
    Q81398 = "Q81398",
    Q96 = "Q96",
}

export interface Geometry {
    type:        string;
    coordinates: number[];
}

export interface Properties {
    wikidata?: Wikidata;
    accuracy?: string;
}
